apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: astro-remote-kpo-binding
  namespace: astro-remote-kpo # The name of the namespace in namespace.yaml.
subjects:
- kind: User
  name: AstroRemoteKPO # The username of the IAM role you used in Step 7.
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: astro-remote-kpo-role # The name of the role in role.yaml.
  apiGroup: rbac.authorization.k8s.io